### ISSUE TITLE
shadowJar task is broken when a function is generated

### ISSUE THREAD

**Issue by lkonya** [micronaut-projects/micronaut-profiles#101]
## Steps to Reproduce
Use CLI to create-function:
1.  `mn create-function test-function`
1.  `cd test-function`
1. `./gradlew clean assemble`

## Expected Behaviour
Fatjar is generated.

## Actual Behaviour
shadowJar task throws exception 
```
Caused by: java.lang.AbstractMethodError
    at com.github.jengelman.gradle.plugins.shadow.transformers.Transformer$modifyOutputStream$2.call(Unknown Source)
    at com.github.jengelman.gradle.plugins.shadow.transformers.Transformer$modifyOutputStream$2.call(Unknown Source)
    at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction$_processTransformers_closure1.doCall(ShadowCopyAction.groovy:134)
    at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction.processTransformers(ShadowCopyAction.groovy:132)
    at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction.this$dist$invoke$1(ShadowCopyAction.groovy)
    at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction$2.methodMissing(ShadowCopyAction.groovy)
    at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction$2.execute(ShadowCopyAction.groovy:112)
    at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction$2$execute.call(Unknown Source)
    at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction.withResource(ShadowCopyAction.groovy:152)
    at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowCopyAction.execute(ShadowCopyAction.groovy:107)
```
The root of the problem is that `"com.amazonaws:aws-lambda-java-log4j2:1.0.0”`, which is automatically added to the build file by the CLI, is require a special setup (see https://docs.aws.amazon.com/lambda/latest/dg/java-logging.html#logging-java-examples).
The gradle counterpart (https://github.com/TheBoegl/shadow-log4j-transformer) discourage the current setup.

To resolve the issue `id "de.sebastianboegl.shadow.transformer.log4j" version “2.1.1”` needs to be removed from the `plugins` and `transform(de.sebastianboegl.gradle.plugins.shadow.transformers.Log4j2PluginsFileTransformer)` should be added to the `shadowJar` task.

**Comment by dan-thomson-bbc** [comment]
I also had this error with Micronaut create-function and added the following to the build.gradle shadowJar task

`shadowJar {
    transform(com.github.jengelman.gradle.plugins.shadow.transformers.Log4j2PluginsCacheFileTransformer)
    mergeServiceFiles()
}`

**Comment by shivamkrpandey** [comment]
> I also had this error with Micronaut create-function and added the following to the build.gradle shadowJar task
> 
> `shadowJar { transform(com.github.jengelman.gradle.plugins.shadow.transformers.Log4j2PluginsCacheFileTransformer) mergeServiceFiles() }`

Thank you it worked.
